version: '3'

services:

  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5431:5432

  discovery-service:
    container_name: discovery-service
    build: discovery
    ports:
      - 9761:9761
    depends_on:
      - postgres-db

  api-gateway:
    container_name: api-gateway
    build: api-gateway
    ports:
      - 9091:9091
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:9761/eureka/
    depends_on:
      - discovery-service

  product-service:
    container_name: product-service
    build: product
    ports:
      - 9095:9095
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:9761/eureka/
    depends_on:
      - discovery-service

  user-service:
    container_name: user-service
    build: user
    ports:
      - 9097:9097
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:9761/eureka/
    depends_on:
      - discovery-service