server:
  port: 9091

spring:
  application:
    name: PROJECT-API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:9095/
          predicates:
            - Path=/product/**
        - id: user-service
          uri: http://localhost:9097/
          predicates:
            - Path=/user/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG