server:
  port: 9091

spring:
  application:
    name: PROJECT-API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product-service:9095/
          predicates:
            - Path=/product/**
        - id: user-service
          uri: http://user-service:9097/
          predicates:
            - Path=/user/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:9761/eureka/
  instance:
    hostname: discovery-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG